/* eslint-disable import/prefer-default-export */
const CATEGORY_BAKING = "baking";
const CATEGORY_BEVERAGES = "beverages";
const CATEGORY_BREAD = "bread";
const CATEGORY_CHEESES = "cheese";
const CATEGORY_CONDIMENTS = "condiments";
const CATEGORY_DAIRY_AND_EGGS = "dairy & eggs";
const CATEGORY_FROZEN_FOOD = "frozen food";
const CATEGORY_FRUITS = "fruits";
const CATEGORY_GRAINS = "grains";
const CATEGORY_HERBS_AND_SPICES = "herbs & spices";
const CATEGORY_INTERNATIONAL = "international";
const CATEGORY_LEGUMES = "legumes";
const CATEGORY_MEATS = "meats";
const CATEGORY_NUTS_AND_SEEDS = "nuts & seeds";
const CATEGORY_OILS_AND_FATS = "oils & fats";
const CATEGORY_PANTRY_ESSENTIALS = "pantry essentials";
const CATEGORY_PASTA = "pasta";
const CATEGORY_SEAFOOD = "seafood";
const CATEGORY_SOUPS_AND_BROTHS = "soups & broths";
const CATEGORY_SWEETS = "sweets";
const CATEGORY_TEA_AND_COFFEE = "tea & coffee";
const CATEGORY_VEGGIES = "vegetables";

export type category =
  | typeof CATEGORY_BAKING
  | typeof CATEGORY_BEVERAGES
  | typeof CATEGORY_BREAD
  | typeof CATEGORY_CHEESES
  | typeof CATEGORY_CONDIMENTS
  | typeof CATEGORY_DAIRY_AND_EGGS
  | typeof CATEGORY_FROZEN_FOOD
  | typeof CATEGORY_FRUITS
  | typeof CATEGORY_GRAINS
  | typeof CATEGORY_HERBS_AND_SPICES
  | typeof CATEGORY_INTERNATIONAL
  | typeof CATEGORY_LEGUMES
  | typeof CATEGORY_MEATS
  | typeof CATEGORY_NUTS_AND_SEEDS
  | typeof CATEGORY_OILS_AND_FATS
  | typeof CATEGORY_PANTRY_ESSENTIALS
  | typeof CATEGORY_PASTA
  | typeof CATEGORY_SEAFOOD
  | typeof CATEGORY_SOUPS_AND_BROTHS
  | typeof CATEGORY_SWEETS
  | typeof CATEGORY_TEA_AND_COFFEE
  | typeof CATEGORY_VEGGIES;

export interface Ingredient {
  name: string;
  categories: category[];
}

export const Categories = {
  BAKING: CATEGORY_BAKING,
  BEVERAGES: CATEGORY_BEVERAGES,
  BREAD: CATEGORY_BREAD,
  CHEESES: CATEGORY_CHEESES,
  CONDIMENTS: CATEGORY_CONDIMENTS,
  DAIRY_AND_EGGS: CATEGORY_DAIRY_AND_EGGS,
  FROZEN_FOOD: CATEGORY_FROZEN_FOOD,
  FRUITS: CATEGORY_FRUITS,
  GRAINS: CATEGORY_GRAINS,
  HERBS_AND_SPICES: CATEGORY_HERBS_AND_SPICES,
  INTERNATIONAL: CATEGORY_INTERNATIONAL,
  LEGUMES: CATEGORY_LEGUMES,
  MEATS: CATEGORY_MEATS,
  NUTS_AND_SEEDS: CATEGORY_NUTS_AND_SEEDS,
  OILS_AND_FATS: CATEGORY_OILS_AND_FATS,
  PANTRY_ESSENTIALS: CATEGORY_PANTRY_ESSENTIALS,
  PASTA: CATEGORY_PASTA,
  SEAFOOD: CATEGORY_SEAFOOD,
  SOUPS_AND_BROTHS: CATEGORY_SOUPS_AND_BROTHS,
  SWEETS: CATEGORY_SWEETS,
  TEA_AND_COFFEE: CATEGORY_TEA_AND_COFFEE,
  VEGGIES: CATEGORY_VEGGIES,
};
